[package]
name = "most"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
num-bigint = "0.4"
reqwest = { version = "0.11", features = ["stream"] }
tokio = { version = "1", features = ["macros", "rt"] }
