[package]
name = "most"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
hyper = { version = "0.14", features = ["http1", "client", "tcp"] }
num-bigint = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "sync"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "rem"
